{{- range .Values.workerPools }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ $.Values.cluster.name }}-{{ .name }}
spec:
  clusterName: {{ $.Values.cluster.name }}
  maxUnhealthy: 100%
  nodeStartupTimeout: 20m
  remediationTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HCloudRemediationTemplate
    name: restart
  selector:
    matchLabels:
      nodepool: {{ $.Values.cluster.name }}-{{ .name }}
  unhealthyConditions:
  - status: Unknown
    timeout: 300s
    type: Ready
  - status: "False"
    timeout: 300s
    type: Ready
{{- end }}
