{{- range .Values.workerPools }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: {{ $.Values.cluster.name }}-{{ .name }}
spec:
  template:
    spec:
      configPatches: {{ toYaml .talosConfigPatches }}
      generateType: worker
      talosVersion: {{ .versions.talos }}
{{- end }}
