{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name | quote }}
  labels:
    {{- if $.Values.common.labels }}
      {{- toYaml $.Values.common.labels | nindent 4 }}
    {{- end }}
    {{- if .labels }}
      {{- toYaml .labels | nindent 4 }}
    {{- end }}
{{- end }}
