{{- range .Values.namespaces }}
  {{- if not (has .name (list "default" "kube-system" "kube-public" "kube-node-lease"))}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name | quote }}
  labels:
    {{- if $.Values.common.labels }}
      {{- toYaml $.Values.common.labels | nindent 4 }}
    {{- end }}
    {{- if .labels }}
      {{- toYaml .labels | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
