# provides defaults that will be overwritten if specified elsewhere
defaults:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 4
    memory: 4Gi

# Rather than being overridden like defaults, common values prepend namespace specific values
common:
  labels:
    common: label

# One can configure a resourceQuota for the following namespaces without it creating the namespaces.
# This is handled automatically by the chart.
# - default
# - kube-system
# - kube-public
# - kube-node-lease
# TODO: The number `0` must be quoted, otherwise it is interpreted as false and skipped over
namespaces:
  - name: namespace-a
    labels:
      specific: label
    requests:
      cpu: 3
      memory: 3Gi
    limits:
      cpu: 3
      memory: 3Gi
  - name: namespace-b
  - name: default
    requests:
      cpu: "0"
      memory: 0Gi
    limits:
      cpu: "0"
      memory: 0Gi
  - name: kube-system
  - name: kube-node-lease
    requests:
      cpu: "0"
      memory: 0Gi
    limits:
      cpu: "0"
      memory: 0Gi
  - name: kube-public
    requests:
      cpu: "0"
      memory: 0Gi
    limits:
      cpu: "0"
      memory: 0Gi
