---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-control-plane
spec:
  template:
    spec:
      imageName: {{ .Values.controlPlane.hcloud.imageName }}
      placementGroupName: control-plane
      type: {{ .Values.controlPlane.hcloud.machineType }}
      publicNetwork:
        enableIPv4: {{ .Values.controlPlane.publicNetwork.enableIPv4 | default true }}
        enableIPv6: {{ .Values.controlPlane.publicNetwork.enableIPv6 | default true }}
